baseURL: "https://janjones.me/"
title: "Jan Jones"
theme: "hugo-PaperMod"

enableRobotsTXT: true

params:
  description: "Jan Jones's blog"
  author: "Jan Jones"

  profileMode:
    enabled: true
    imageUrl: "me.jpg"
    imageTitle: "Jan Jones's profile picture"
    subtitle: "Follow me on [Twitter](https://twitter.com/jjonescz) or [Reddit](https://www.reddit.com/user/jjones_cz/) for new posts."
    buttons:
      - name: Blog
        url: /posts
      - name: Projects
        url: /projects

  socialIcons:
    - name: email
      url: mailto:jan@knowledgepicker.com
    - name: linkedin
      url: https://www.linkedin.com/in/jan-jones-cz/
    - name: github
      url: https://github.com/jjonescz
    - name: stackoverflow
      url: https://stackoverflow.com/users/9080566/jan-jone%c5%a1
    - name: twitter
      url: https://twitter.com/jjonescz
    - name: paypal
      url: https://www.paypal.me/jjonescz
    - name: other
      url: https://jan-a.tech/jan/

menu:
  main:
    - identifier: about
      name: About
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /posts
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
