baseURL: "https://janjones.me/"
title: "Jan Jones"
theme: "hugo-PaperMod"

enableRobotsTXT: true

params:
  description: "Jan Jones's blog"
  author: "Jan Jones"

  profileMode:
    enabled: true
    imageUrl: "me.jpg"
    imageTitle: "Jan Jones's profile picture"
